- name: create db container
  containers.podman.podman_container:
    name: rss_json
    state: present
    image: postgres:alpine
    ports:
      - "5432:5432"
    env:
      POSTGRES_DB: "rss_json"
      POSTGRES_PASSWORD: "{{db_password}}"

- name: test
  shell: |
      /usr/bin/psql postgresql://postgres:{{db_password}}@localhost:5432/rss_json << EOF
      {{lookup('template', '../pg-scripts/2021-06-13_create_db.sql') }}
      EOF
